/**:
  ros__parameters:
    aruco_marker_info:
      '1':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackRook1'
        link: 'None'
      '2':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackPawn1'
        link: 'None'
      '3':
        length_mm: 20
        use_rgb_only: False
        name: 'WhitePawn1'
        link: 'None'
      '4':
        length_mm: 20
        use_rgb_only: False
        name: 'WhiteRook1'
        link: 'None'
      '5':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackKnight1'
        link: 'None'
      '6':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackPawn2'
        link: 'None'
      '7':
        length_mm: 20
        use_rgb_only: False
        name: 'WhitePawn2'
        link: 'None'
      '8':
        length_mm: 20
        use_rgb_only: False
        name: 'WhiteKnight1'
        link: 'None'
      '9':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackBishop1'
        link: 'None'
      '10':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackPawn3'
        link: 'None'
      '11':
        length_mm: 20
        use_rgb_only: False
        name: 'WhitePawn3'
        link: 'None'
      '12':
        length_mm: 20
        use_rgb_only: False
        name: 'WhiteBishop1'
        link: 'None'
      '13':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackKing1'
        link: 'None'
      '14':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackPawn4'
        link: 'None'
      '15':
        length_mm: 20
        use_rgb_only: False
        name: 'WhitePawn4'
        link: 'None'
      '16':
        length_mm: 20
        use_rgb_only: False
        name: 'WhiteKing1'
        link: 'None'
      '17':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackQueen1'
        link: 'None'
      '18':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackPawn5'
        link: 'None'
      '19':
        length_mm: 20
        use_rgb_only: False
        name: 'WhitePawn5'
        link: 'None'
      '20':
        length_mm: 20
        use_rgb_only: False
        name: 'WhiteQueen1'
        link: 'None'
      '21':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackBishop2'
        link: 'None'
      '22':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackPawn6'
        link: 'None'
      '23':
        length_mm: 20
        use_rgb_only: False
        name: 'WhitePawn6'
        link: 'None'
      '24':
        length_mm: 20
        use_rgb_only: False
        name: 'WhiteBishop2'
        link: 'None'
      '25':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackKnight2'
        link: 'None'
      '26':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackPawn7'
        link: 'None'
      '27':
        length_mm: 20
        use_rgb_only: False
        name: 'WhitePawn7'
        link: 'None'
      '28':
        length_mm: 20
        use_rgb_only: False
        name: 'WhiteKnight2'
        link: 'None'
      '29':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackRook2'
        link: 'None'
      '30':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackPawn8'
        link: 'None'
      '31':
        length_mm: 20
        use_rgb_only: False
        name: 'WhiteRook2'
        link: 'None'
      '32':
        length_mm: 20
        use_rgb_only: False
        name: 'WhitePawn8'
        link: 'None'
      '33':
        length_mm: 18
        use_rgb_only: False
        name: 'FileAW'
        link: 'None'
      '34':
        length_mm: 18
        use_rgb_only: False
        name: 'FileBW'
        link: 'None'
      '35':
        length_mm: 18
        use_rgb_only: False
        name: 'FileCW'
        link: 'None'
      '36':
        length_mm: 18
        use_rgb_only: False
        name: 'FileDW'
        link: 'None'
      '37':
        length_mm: 18
        use_rgb_only: False
        name: 'FileEW'
        link: 'None'
      '38':
        length_mm: 18
        use_rgb_only: False
        name: 'FileFW'
        link: 'None'
      '39':
        length_mm: 18
        use_rgb_only: False
        name: 'FileGW'
        link: 'None'
      '40':
        length_mm: 18
        use_rgb_only: False
        name: 'FileHW'
        link: 'None'
      '41':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank1W'
        link: 'None'
      '42':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank2W'
        link: 'None'
      '43':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank3W'
        link: 'None'
      '44':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank4W'
        link: 'None'
      '45':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank5W'
        link: 'None'
      '46':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank6W'
        link: 'None'
      '47':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank7W'
        link: 'None'
      '48':
        length_mm: 18
        use_rgb_only: False
        name: 'FileAB'
        link: 'None'
      '49':
        length_mm: 18
        use_rgb_only: False
        name: 'FileBB'
        link: 'None'
      '50':
        length_mm: 18
        use_rgb_only: False
        name: 'FileCB'
        link: 'None'
      '51':
        length_mm: 18
        use_rgb_only: False
        name: 'FileDB'
        link: 'None'
      '52':
        length_mm: 18
        use_rgb_only: False
        name: 'FileEB'
        link: 'None'
      '53':
        length_mm: 18
        use_rgb_only: False
        name: 'FileFB'
        link: 'None'
      '54':
        length_mm: 18
        use_rgb_only: False
        name: 'FileGB'
        link: 'None'
      '55':
        length_mm: 18
        use_rgb_only: False
        name: 'FileHB'
        link: 'None'
      '56':
        length_mm: 18
        use_rgb_only: False
        name: 'WhitePromo'
        link: 'None'
      '57':
        length_mm: 18
        use_rgb_only: False
        name: 'BlackPromo'
        link: 'None'
      '58':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank1B'
        link: 'None'
      '59':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank2B'
        link: 'None'
      '60':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank3B'
        link: 'None'
      '61':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank4B'
        link: 'None'
      '62':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank5B'
        link: 'None'
      '63':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank6B'
        link: 'None'
      '64':
        length_mm: 18
        use_rgb_only: False
        name: 'Rank7B'
        link: 'None'
      '65':
        length_mm: 20
        use_rgb_only: False
        name: 'WhiteQueen2'
        link: 'None'
      '66':
        length_mm: 20
        use_rgb_only: False
        name: 'WhiteQueen3'
        link: 'None'
      '67':
        length_mm: 20
        use_rgb_only: False
        name: 'WhiteKnight3'
        link: 'None'
      '68':
        length_mm: 20
        use_rgb_only: False
        name: 'WhiteKnight4'
        link: 'None'
      '69':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackQueen2'
        link: 'None'
      '70':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackQueen3'
        link: 'None'
      '71':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackKnight3'
        link: 'None'
      '72':
        length_mm: 20
        use_rgb_only: False
        name: 'BlackKnight4'
        link: 'None'
      '200':
        length_mm: 14.0
        use_rgb_only: true
        name: 'finger_left'
        link: 'link_finger_left'
      '201':
        length_mm: 14.0
        use_rgb_only: true
        name: 'finger_right'
        link: 'link_finger_right'
      'default':
        length_mm: 18
        use_rgb_only: False
        name: 'unknown'
        link: 'None'