# Request (Client -> Server)
# Should be [a-h][1-8]
string start_rank
string start_file
string end_rank
string end_file
string start_piece
string end_piece
---
# Response (Server -> Client)
string message
bool success